version: "3.9"  
services:
    node:
        build: "."
        container_name: "node-container"
        restart: "always"
        ports:
            - "3030:3030"
        volumes:
            - "./:/app"
        depends_on:
            - database
    database:
        image: mysql
        container_name: "mysql-container"
        restart: "always"
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_DATABASE: "project_database"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes: 
            - "./database/mysql:/var/lib/mysql"
        ports:
            - "3306:3306"

